#install Docker and docker compose plugins

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

version: '3.9'

services:
  # Creating the Mongodb service for the backend
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - mongo-net

  # Running the frontend container
  yolofrontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb
      DBNAME: nixip2
    depends_on:
      - mongodb
    networks:
      - mongo-net
  volumes:
      - mongo-data:/data/db 


  # Running the backend container 
  yoloimage:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/nixip2
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mongo-net

# Creating the network for communication
networks:
  mongo-net:
    driver: bridge
