#install Docker and docker compose plugins

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app
version: "3.8"

services:
  yolo-backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - yolo-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - yolo-network

volumes:
  app-mongo-data:

networks:
  yolo-network:
    driver: bridge
