---
# Play 1: Clone the yolo GitHub repository
- name: Clone yolo project repository
  hosts: all
  become: true
  tasks:
    - name: Ensure Git is installed
      apt:
        name: git
        state: present
        update_cache: yes
      tags: git

    - name: Clone yolo project repository
      git:
        repo: https://github.com/kipyegonrotich/yolo.git
        dest: /home/vagrant/yolo
        version: master
      tags: clone

# Play 2: Ensure Docker network exists
- name: Ensure Docker network exists
  hosts: all
  become: true
  tasks:
    - name: Create Docker network app-net
      community.docker.docker_network:
        name: app-net
        state: present

# Play 3: Run role-based deployments
- name: IP3 Ansible playbook
  hosts: all
  become: true
  roles: 
    - mongodb
    - frontend
    - backend