---
- name: Run backend container
  docker_container:
    name: yolo-backend
    image: kipyegonrotich/yolo-backend:v1.0.0
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    env:
      MONGO_URI: mongodb://mongodb_container:27017/yolo
    networks:
      - name: app-net










#name: Pull image from repository
 # docker_image:
  #  name: kipyegonrotich/yolo-backend
   # tag: v1.0.0
    #source: pull

#- name: Create Node.js Backend Container
 # docker_container:
  #  name: yoloimage
   # image: kipyegonrotich/yolo-backend:v1.0.0
    #networks:
     # - name: app-net
    #ports:
     # - "5000:5000"
    #command: "npm start"
  #become: yes