all:
  hosts:
    appserver:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/nix/development/code/dev10/docker/yolo/.vagrant/machines/default/virtualbox/private_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
