---
- name: Deploy Yolo Backend
  hosts: localhost
  become: true
  # Define configuration variables

  vars:
    backend_image: kipyegonrotich/yolo-backend:v1.0.0   
    backend_container: yoloimage                        
    backend_port: "5000"                                
    mongo_uri: "mongodb://mongodb:27017/nixip2"         
    mongo_network: mongo-net                            

  tasks:
      # Step 1: Ensure Docker network exists
  
    - name: Ensure Docker network exists
      docker_network:
        name: "{{ mongo_network }}"
        driver: bridge

 
    # Step 2: Pull the backend Docker image
    - name: Pull backend Docker image
      docker_image:
        name: "{{ backend_image }}"
        source: pull

    
    # Step 3: Run the backend container
    - name: Run Yolo backend container
      docker_container:
        name: "{{ backend_container }}"
        image: "{{ backend_image }}"
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        env:
          MONGO_URI: "{{ mongo_uri }}"
        networks:
          - name: "{{ mongo_network }}"
        restart_policy: always
        state: started
